Course : MACHINE LEARNING WITH DEPLOYMENT AND DEEP LEARNING

Numpy Assignment - By Subham Bagchi

1. Write a function so that the columns of the output matrix are powers of the input
   vector.
   The order of the powers is determined by the increasing boolean argument. Specifically, when
   increasing is False, the i-th output column is the input vector raised element-wise to the power
   of N - i - 1.
   HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
         Theophile Vandermonde.

In [27]:
import numpy as np

def vander_mat(l,n,increasing=False):
    
    if increasing:
        p = np.array([j**i for j in l for i in range(n)]).reshape(len(l),n)
    else:
        p = np.array([j**(n-i-1) for j in l for i in range(n)]).reshape(len(l),n)
    return p

list1 = [1,2,3,4,5]
n1 = 5
out_dec_mat = vander_mat(list1,n1,False)
out_inc_mat = vander_mat(list1,n1,increasing=True)

print('Vander matrix in decreasing order of powers')
print('-'*50)
print(out_dec_mat)
print('\n')

print('Vander matrix in increasing order of powers')
print('-'*50)
print(out_inc_mat)
            

Vander matrix in decreasing order of powers
--------------------------------------------------
[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


Vander matrix in increasing order of powers
--------------------------------------------------
[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]


2. Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
   the given sequence is defined as follows:
 
 The moving average sequence has n-k+1 elements as shown below.
 
 The moving averages with k=4 of a ten-value sequence (n=10) is shown below
 
 i 1 2 3 4 5 6 7 8 9 10
 
 Input 10 20 30 40 50 60 70 80 90 100
 
   y1 25 = (10+20+30+40)/4
   
   y2 35 = (20+30+40+50)/4
   
   y3 45 = (30+40+50+60)/4
   
   y4 55 = (40+50+60+70)/4
   
   y5 65 = (50+60+70+80)/4
   
   y6 75 = (60+70+80+90)/4
   
   y7 85 = (70+80+90+100)/4

 Thus, the moving average sequence has n-k+1=10-4+1=7 values.
 
 Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.
  

In [61]:
def moving_average(l,n):
    result = []
    for i in range(len(l)):
        if i <= len(l)-n :
            result.append((l[i]+l[i+1]+l[i+2])/n)
        else:
            break
    return result

list1 = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
N = 3
k = len(list1)-N+1
p = moving_average(list1,N)
t = np.round(p,2)
print('Moving Average values : ', list(t))
print('\n')
print('Length of list : ',k)
        

Moving Average values :  [5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]


Length of list :  11
